## FIRST INNINGS SCORE PREDICTION

# OBJECTIVE :
          *The Project I have done is First Innings Score Prediction using Machine Learning.
          *This will Predict the Score of the First Innings by taking the overs, after 5 in order get the Overview of the Match.

In [1]:
# Importing essential libraries
import pandas as pd
import pickle

# Loading the dataset
df = pd.read_csv('ipl11.csv')

In [2]:
df.head()

mid        date                  venue               bat_team  \
0    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
1    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
2    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
3    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
4    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   

                     bowl_team      batsman   bowler  runs  wickets  overs  \
0  Royal Challengers Bangalore   SC Ganguly  P Kumar     1        0    0.1   
1  Royal Challengers Bangalore  BB McCullum  P Kumar     1        0    0.2   
2  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.2   
3  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.3   
4  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.4   

   runs_last_5  wickets_last_5  striker  non-striker  total  
0            1               0        0            0    222  
1            1               0        0            0    222  
2            2               0        0            0    222  
3            2               0        0            0    222  
4            2               0        0            0    222

In [3]:
# --- Data Cleaning ---
# Removing unwanted columns
columns_to_remove = ['mid', 'batsman', 'bowler', 'striker', 'non-striker']
df.drop(labels=columns_to_remove, axis=1, inplace=True)

In [4]:
df.head()

date                  venue               bat_team  \
0  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
2  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
3  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
4  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   

                     bowl_team  runs  wickets  overs  runs_last_5  \
0  Royal Challengers Bangalore     1        0    0.1            1   
1  Royal Challengers Bangalore     1        0    0.2            1   
2  Royal Challengers Bangalore     2        0    0.2            2   
3  Royal Challengers Bangalore     2        0    0.3            2   
4  Royal Challengers Bangalore     2        0    0.4            2   

   wickets_last_5  total  
0               0    222  
1               0    222  
2               0    222  
3               0    222  
4               0    222

In [5]:
df['bat_team'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Deccan Chargers', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Daredevils',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant'], dtype=object)

In [6]:
# Keeping only consistent teams
consistent_teams = ['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
                    'Mumbai Indians', 'Kings XI Punjab', 'Royal Challengers Bangalore',
                    'Delhi Daredevils', 'Sunrisers Hyderabad']

In [7]:
df = df[(df['bat_team'].isin(consistent_teams)) & (df['bowl_team'].isin(consistent_teams))]

In [8]:
# Removing the first 5 overs data in every match
df = df[df['overs']>=5.0]

In [9]:
df.head()

date                  venue               bat_team  \
32  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
33  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
34  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
35  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
36  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   

                      bowl_team  runs  wickets  overs  runs_last_5  \
32  Royal Challengers Bangalore    61        0    5.1           59   
33  Royal Challengers Bangalore    61        1    5.2           59   
34  Royal Challengers Bangalore    61        1    5.3           59   
35  Royal Challengers Bangalore    61        1    5.4           59   
36  Royal Challengers Bangalore    61        1    5.5           58   

    wickets_last_5  total  
32               0    222  
33               1    222  
34               1    222  
35               1    222  
36               1    222

In [10]:
print(df['bat_team'].unique())
print(df['bowl_team'].unique())

['Kolkata Knight Riders' 'Chennai Super Kings' 'Rajasthan Royals'
 'Mumbai Indians' 'Kings XI Punjab' 'Royal Challengers Bangalore'
 'Delhi Daredevils' 'Sunrisers Hyderabad']
['Royal Challengers Bangalore' 'Kings XI Punjab' 'Delhi Daredevils'
 'Rajasthan Royals' 'Mumbai Indians' 'Chennai Super Kings'
 'Kolkata Knight Riders' 'Sunrisers Hyderabad']


In [11]:
# Converting the column 'date' from string into datetime object
from datetime import datetime
df['date'] = df['date'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d'))

In [12]:
# --- Data Preprocessing ---
# Converting categorical features using OneHotEncoding method
encoded_df = pd.get_dummies(data=df, columns=['bat_team', 'bowl_team'])

In [13]:
encoded_df

date                  venue  runs  wickets  overs  runs_last_5  \
32    2008-04-18  M Chinnaswamy Stadium    61        0    5.1           59   
33    2008-04-18  M Chinnaswamy Stadium    61        1    5.2           59   
34    2008-04-18  M Chinnaswamy Stadium    61        1    5.3           59   
35    2008-04-18  M Chinnaswamy Stadium    61        1    5.4           59   
36    2008-04-18  M Chinnaswamy Stadium    61        1    5.5           58   
...          ...                    ...   ...      ...    ...          ...   
75884 2017-05-19  M Chinnaswamy Stadium   106        9   18.1           29   
75885 2017-05-19  M Chinnaswamy Stadium   107        9   18.2           29   
75886 2017-05-19  M Chinnaswamy Stadium   107        9   18.3           28   
75887 2017-05-19  M Chinnaswamy Stadium   107        9   18.4           24   
75888 2017-05-19  M Chinnaswamy Stadium   107       10   18.5           23   

       wickets_last_5  total  bat_team_Chennai Super Kings  \
32                  0    222                             0   
33                  1    222                             0   
34                  1    222                             0   
35                  1    222                             0   
36                  1    222                             0   
...               ...    ...                           ...   
75884               4    107                             0   
75885               4    107                             0   
75886               4    107                             0   
75887               4    107                             0   
75888               5    107                             0   

       bat_team_Delhi Daredevils  ...  bat_team_Royal Challengers Bangalore  \
32                             0  ...                                     0   
33                             0  ...                                     0   
34                             0  ...                                     0   
35                             0  ...                                     0   
36                             0  ...                                     0   
...                          ...  ...                                   ...   
75884                          0  ...                                     0   
75885                          0  ...                                     0   
75886                          0  ...                                     0   
75887                          0  ...                                     0   
75888                          0  ...                                     0   

       bat_team_Sunrisers Hyderabad  bowl_team_Chennai Super Kings  \
32                                0                              0   
33                                0                              0   
34                                0                              0   
35                                0                              0   
36                                0                              0   
...                             ...                            ...   
75884                             0                              0   
75885                             0                              0   
75886                             0                              0   
75887                             0                              0   
75888                             0                              0   

       bowl_team_Delhi Daredevils  bowl_team_Kings XI Punjab  \
32                              0                          0   
33                              0                          0   
34                              0                          0   
35                              0                          0   
36                              0                          0   
...                           ...                        ...   
75884                           0                          0   
75885                       

In [14]:
encoded_df.columns

Index(['date', 'venue', 'runs', 'wickets', 'overs', 'runs_last_5',
       'wickets_last_5', 'total', 'bat_team_Chennai Super Kings',
       'bat_team_Delhi Daredevils', 'bat_team_Kings XI Punjab',
       'bat_team_Kolkata Knight Riders', 'bat_team_Mumbai Indians',
       'bat_team_Rajasthan Royals', 'bat_team_Royal Challengers Bangalore',
       'bat_team_Sunrisers Hyderabad', 'bowl_team_Chennai Super Kings',
       'bowl_team_Delhi Daredevils', 'bowl_team_Kings XI Punjab',
       'bowl_team_Kolkata Knight Riders', 'bowl_team_Mumbai Indians',
       'bowl_team_Rajasthan Royals', 'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad'],
      dtype='object')

In [15]:
# Rearranging the columns
encoded_df = encoded_df[['date', 'bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils', 'bat_team_Kings XI Punjab',
              'bat_team_Kolkata Knight Riders', 'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
              'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
              'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils', 'bowl_team_Kings XI Punjab',
              'bowl_team_Kolkata Knight Riders', 'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
              'bowl_team_Royal Challengers Bangalore', 'bowl_team_Sunrisers Hyderabad',
              'overs', 'runs', 'wickets', 'runs_last_5', 'wickets_last_5', 'total']]

In [16]:
# Splitting the data into train and test set
X_train = encoded_df.drop(labels='total', axis=1)[encoded_df['date'].dt.year <= 2016]
X_test = encoded_df.drop(labels='total', axis=1)[encoded_df['date'].dt.year >= 2017]

In [17]:
y_train = encoded_df[encoded_df['date'].dt.year <= 2016]['total'].values
y_test = encoded_df[encoded_df['date'].dt.year >= 2017]['total'].values

In [18]:
encoded_df['total'].values

array([222, 222, 222, ..., 107, 107, 107], dtype=int64)

In [19]:
y_train

array([222, 222, 222, ..., 208, 208, 208], dtype=int64)

In [20]:
y_test

array([207, 207, 207, ..., 107, 107, 107], dtype=int64)

In [21]:
# Removing the 'date' column
X_train.drop(labels='date', axis=True, inplace=True)
X_test.drop(labels='date', axis=True, inplace=True)

In [22]:
# --- Model Building ---
# Linear Regression Model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [23]:
regressor.predict(X_test)

array([172.07093429, 175.2197967 , 174.61607874, ..., 100.37504751,
        99.80473879,  93.14382211])

In [24]:
# Creating a pickle file for the classifier
filename = 'first-innings-score-lr-model.pkl'
pickle.dump(regressor, open(filename, 'wb'))

## Ridge Regression

In [25]:
## Ridge Regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import RandomizedSearchCV

In [26]:
ridge=Ridge()
parameters={'alpha':[1e-13,1e-11,1e-9,1e-5,1e-2,1,7,17,24,31,37,40]}
ridge_regressor=RandomizedSearchCV(ridge,parameters,scoring='neg_mean_squared_error',cv=10)
ridge_regressor.fit(X_train,y_train)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:212: LinAlgWarning: Ill-conditioned matrix (rcond=1.62441e-19): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:212: LinAlgWarning: Ill-conditioned matrix (rcond=9.18025e-20): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:212: LinAlgWarning: Ill-conditioned matrix (rcond=9.91852e-21): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:212: LinAlgWarning: Ill-conditioned matrix (rcond=8.61947e-20): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:21

RandomizedSearchCV(cv=10, estimator=Ridge(),
                   param_distributions={'alpha': [1e-13, 1e-11, 1e-09, 1e-05,
                                                  0.01, 1, 7, 17, 24, 31, 37,
                                                  40]},
                   scoring='neg_mean_squared_error')

In [27]:

print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

{'alpha': 40}
-326.17628966626864


In [28]:
prediction=ridge_regressor.predict(X_test)

In [30]:
from sklearn import metrics
import numpy as np
print('MAE:', metrics.mean_absolute_error(y_test, prediction))
print('MSE:', metrics.mean_squared_error(y_test, prediction))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, prediction)))

MAE: 12.117294527005019
MSE: 251.03172964112724
RMSE: 15.843980864704655


## Lasso Regression

In [31]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import RandomizedSearchCV

In [32]:
lasso=Lasso()
parameters={'alpha':[1e-13,1e-11,1e-9,1e-5,1e-2,1,7,17,24,31,37,40]}
lasso_regressor=RandomizedSearchCV(lasso,parameters,scoring='neg_mean_squared_error',cv=10)

lasso_regressor.fit(X_train,y_train)
print(lasso_regressor.best_params_)
print(lasso_regressor.best_score_)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.452e+05, tolerance: 2.832e+03
  model = cd_fast.enet_coordinate_descent(
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.775e+05, tolerance: 2.977e+03
  model = cd_fast.enet_coordinate_descent(
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.734e+05, toleranc

{'alpha': 1}
-320.9085017331346


In [33]:
prediction1=lasso_regressor.predict(X_test)

In [34]:
prediction1

array([170.85983934, 174.24824974, 173.46897392, ..., 105.86186741,
       104.87877323,  98.9709836 ])

In [35]:
from sklearn import metrics
import numpy as np
print('MAE:', metrics.mean_absolute_error(y_test, prediction1))
print('MSE:', metrics.mean_squared_error(y_test, prediction1))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, prediction1)))

MAE: 12.214053814850246
MSE: 262.3797366400714
RMSE: 16.19813991296752


# XGB Boost

In [36]:
from xgboost import XGBRegressor

In [37]:
xgboost=XGBRegressor()
parameters={'alpha':[1e-13,1e-11,1e-9,1e-5,1e-2,1,7,17,24,31,37,40]}
xgboost_regressor=RandomizedSearchCV(ridge,parameters,scoring='neg_mean_squared_error',cv=10)
xgboost_regressor.fit(X_train,y_train)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:212: LinAlgWarning: Ill-conditioned matrix (rcond=1.40604e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:212: LinAlgWarning: Ill-conditioned matrix (rcond=1.36584e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:212: LinAlgWarning: Ill-conditioned matrix (rcond=1.37946e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:212: LinAlgWarning: Ill-conditioned matrix (rcond=1.40733e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:21

RandomizedSearchCV(cv=10, estimator=Ridge(),
                   param_distributions={'alpha': [1e-13, 1e-11, 1e-09, 1e-05,
                                                  0.01, 1, 7, 17, 24, 31, 37,
                                                  40]},
                   scoring='neg_mean_squared_error')

In [38]:
prediction2=xgboost_regressor.predict(X_test)

In [39]:
from sklearn import metrics
import numpy as np
print('MAE:', metrics.mean_absolute_error(y_test, prediction2))
print('MSE:', metrics.mean_squared_error(y_test, prediction2))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, prediction2)))

MAE: 12.117294527005019
MSE: 251.03172964112724
RMSE: 15.843980864704655
